# ======================================================
#                StorePlugin Configuration
# ======================================================

store-settings:
  # Channels to send the message (true/false)
  send-chat: true
  send-actionbar: false
  send-bossbar: false

  # Dynamically register aliases from config (Requires Server Restart)
  command-aliases:
    - "magaza"
    - "market"

  # MiniMessage Formatted Chat Messages (Multi-line Support)
  # <click:open_url:'YOUR_LINK'> is used for the clickable text.
  chat-message:
    - ""
    - "<white>Please visit our Store</white>"
    - "<click:open_url:'https://mustafa8907.com.tr'><aqua><b>[Click]</b></aqua></click>"
    - "<gray>Buy Rank Cosmetics and more...</gray>"
    - ""

  actionbar-message: "<yellow>Don't miss the discount: <green>NEXUS20"
  bossbar-message: "<aqua><b>Winter Sale Event is Active!</b></aqua>"
  
  # Bossbar Customizations
  # Colors: PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
  bossbar-color: "GREEN"
  # Styles: PROGRESS, NOTCHED_6, NOTCHED_10, NOTCHED_12, NOTCHED_20
  bossbar-overlay: "PROGRESS"
  # Bossbar display duration (in seconds)
  bossbar-duration: 6

  # Sound Settings (Bukkit Sound Enum)
  sound: "ENTITY_PLAYER_LEVELUP"
  sound-volume: 1.0
  sound-pitch: 1.2
